version: '3.8'
name: vs-stack
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
     # - PASSWORD=Aspen1977! #optional
      - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=Aspen1977! #optional
      - SUDO_PASSWORD_HASH= #optional
      - PROXY_DOMAIN=eino.co.uk #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      - code-server-config:/config
      - code-server-files:/config/workspace
     # - file-mounts:/config/workspace/AGAR/container-storage-volumes
      - container-configs:/config/workspace/AGAR/container-config-volumes
    ports:
      - 8443:8443
    restart: unless-stopped

    