version: '3'
services:
    jellyseerr:
       image: fallenbagel/jellyseerr:latest
       container_name: jellyseerr
       environment:
          - LOG_LEVEL=debug
          - PUID=1000
          - PGID=1000
          - TZ=Europe/London
       ports:
          - 5055:5055
       volumes:
          - jellyseerr-config:/app/config
       restart: unless-stopped