version: '3'
services:
  prowlarr:
    image: hotio/prowlarr
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - prowlarr-config:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      - media_network  