version: '3'
services:
  radarr:
    container_name: radarr
    image: hotio/radarr
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=1000 # default user id, defined in .env
      - PGID=1000 # default group id, defined in .env
      - TZ=Europe/London # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - radarr-config:/config # config files
      - media-movies:/movies # movies folder
      - Downloads:/downloads # download folder
    networks:
      - media_network
networks:
  media_network:
    name: media_network
    external: true
